spring.application.name=vda-ledger
spring.profiles.active=dev

#loads the env file and its variables
spring.config.import=optional:file:.env[.properties] 

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

app.ingestion.chunk-size=500

app.rate-limit.ingestion.max-requests=10
app.rate-limit.ingestion.window-seconds=60

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
